### ISSUE TITLE
Pre-included test fails

### ISSUE THREAD

**Issue by trentwritescode** [zapier/zapier-platform-example-app-create#2]
### Description

The test included with this example app is not passible by the basic code provided with the app.

### Steps to reproduce

- Run ``zapier init --template=create {appName}``
- Run ``cd {appName}``
- Run ``npm install``
- Run ``zapier test``

The test will fail, producing the following output:

```
$ zapier test

Validating project locally.
No structural errors found during validation routine.
This project is structurally sound!

Checking app style.
No style errors found during validation routine.
Your app looks great!

Adding /home/vagrant/.zapierrc to environment as ZAPIER_DEPLOY_KEY...
Running test suite.


  creates
    create recipe create
      1) should create a new recipe


  0 passing (132ms)
  1 failing

  1) creates create recipe create should create a new recipe:
     AssertionError: expected 'Max number of elements reached for this resource!' to have property name
      at Assertion.fail (node_modules/should/cjs/should.js:258:17)
      at Assertion.value [as property] (node_modules/should/cjs/should.js:335:19)
      at appTester.then (test/creates.js:20:30)
  From previous event:
      at Context.it (test/creates.js:19:10)





Error! 
(Use --debug flag and run this command again to get more details.)
```

**Comment by bcooksey** [comment]
Gonna move discussion over to https://github.com/zapier/zapier-platform-cli/issues/219 as this affects all example apps that create records.
